kubepug/kubepug

- .deepsource.toml
> Enable Deepsource

- .gitignore
- .whitesource
- README.md
- cmd/kubepug.go
- go.mod
- pkg/kubepug/converter.go
- pkg/kubepug/types.go
- pkg/kubepug/walker.go
Some code cleanup as suggested by Deepsource, BetterCodeHub and CodeBeat
> Code cleanup

- pkg/kubepug/walker.go
This PR makes kubepug ignore the CRDs objects
> Remove crds

- pkg/kubepug/converter.go
- pkg/kubepug/downloader.go
Fixes #13 
This PR uses unstructured.X methods from kubernetes libraries instead of using a lot of "fors"
> Change to unstructured methods

- .goreleaser.yaml
- .krew.yaml
- go.sum
This prepares the plugin for Krew publication
Fixes: #10
> Generate krew schema

- cmd/kubepug.go
- pkg/kubepug/converter.go
- pkg/kubepug/k8sdeprecated.go
- pkg/kubepug/types.go
- pkg/kubepug/walker.go
> Use methods instead of passing them as arguments

- .github/workflows/ci.yaml
- go.mod
- go.sum
> Add Github Action CI

- README.md
Adds Air-Gapped documentation
How to test when there is no internet access
fixes #39 
Signed-off-by: Vicente Zepeda Mas <vzepedamas@suse.com>
> Add Air-Gapped documentation

- cmd/kubepug.go
- go.mod
- go.sum
- lib/kubepug.go
- pkg/formatter/stdout.go
- pkg/kubepug/converter.go
- pkg/kubepug/downloader.go
- pkg/kubepug/k8sdeprecated.go
- pkg/kubepug/types.go
- pkg/kubepug/walker.go
Fixes: #63, #62, #60 
This PR solves:
* Performance issues in kubepug
* Resolves an issue with walker 
* Adds some logging, replace the 'panic' calls and also allowing to debug problems
> Performance and Walker bug fix and add logging

- cmd/kubepug.go
- go.mod
- go.sum
- pkg/kubepug/converter.go
Add the flag ``--error-on-deprecated`` and ``error-on-deleted`` that exists Pug with an error when objects of a deprecated or deleted apis are found.
Fixes: #67
> Add error-on-found when object found

- README.md
Fixes #83, unless I understood the intention of the issue creator wrong. :)
> Fix #83 | Add a sample GitHub Workflow section to docs.

- .github/workflows/ci.yaml
- pkg/formatter/plain.go
- pkg/formatter/stdout.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- pkg/utils/downloader_test.go
This PR adds initial tests and fixes some bugs found during the tests development :+1: 
Fixes partially #27
> Add initial unit tests

- .github/workflows/ci.yaml
- .github/workflows/lint.yml
- .golangci.yml
- cmd/kubepug.go
- lib/kubepug.go
- pkg/formatter/doc.go
- pkg/formatter/formatter.go
- pkg/formatter/json.go
- pkg/formatter/plain.go
- pkg/formatter/stdout.go
- pkg/formatter/yaml.go
- pkg/kubepug/deprecator.go
- pkg/kubepug/fileinput.go
- pkg/kubepug/input/file/deleted.go
- pkg/kubepug/input/file/deprecated.go
- pkg/kubepug/input/file/doc.go
- pkg/kubepug/input/file/utils.go
- pkg/kubepug/input/k8s/deleted.go
- pkg/kubepug/input/k8s/deprecated.go
- pkg/kubepug/input/k8s/doc.go
- pkg/kubepug/input/k8s/resources.go
- pkg/kubepug/k8sinput.go
- pkg/parser/doc.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- pkg/results/doc.go
- pkg/results/list.go
- pkg/utils/doc.go
- pkg/utils/downloader.go
- pkg/utils/downloader_test.go
- add golangci-lint dedicated job
there is a lot of lints to fix
> add golangci-lint dedicated job

- pkg/kubepug/input/file/deleted.go
> fix group bug

- pkg/kubepug/input/file/utils.go
Sometimes we receive a kind List :)
We should lift the yaml and add them into the list of objects to be analyzed
Thanks @knelasevero for the issue and the patience :P 
Fixes #111
> Support Kubernetes List type in file input

- pkg/kubepug/input/k8s/deleted.go
- pkg/kubepug/input/k8s/deprecated.go
> Add missing error output for better debugging

- pkg/kubepug/input/k8s/deleted.go
The client library is returning the same results for "extensions/v1beta1/Ingress" and for "networking.k8s.io/v1/Ingress"
> Removes the false positives deleted ingresses

- cmd/root.go
- lib/kubepug.go
- pkg/kubepug/input/k8s/deleted.go
- pkg/kubepug/k8sinput.go
Some linter messages are annoying, but needs to be fixed...
> Fix annoying linter warnings

- .github/dependabot.yml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- .ko.yaml
- .krew.yaml
- Makefile
- scripts/ko-sign-release-images.sh
- Updates on ci and sign binaries and images with cosign
rehearsal: https://github.com/cpanato/kubepug/releases/tag/v99.99.01
job: https://github.com/cpanato/kubepug/actions/runs/4649977502/jobs/8228692130 failed in the krew but that is expected running in a fork
> Updates on ci and sign binaries and images with cosign

- pkg/kubepug/input/k8s/k8sinput.go
I am stupid and forgot to re-add the validation of aggregated APIs, to ignore them on discovery :)
Re-adding it.
Fixes #413
> Remove aggregated apis from parsing

- generator/deprecations/gen.go
- generator/deprecations/gen_test.go
- go.mod
- lib/kubepug.go
- lib/kubepug_test.go
- pkg/kubepug/deprecator_test.go
- pkg/store/generatedstore/store_test.go
- pkg/store/mock/data.go
- pkg/store/mock/mock.go
- pkg/store/mock/mock_test.go
- pkg/utils/downloader_test.go
> Add some more unit tests

- .github/workflows/ci.yaml
- .github/workflows/lint.yml
- .github/workflows/page.yml
- .github/workflows/release.yaml
- generator/deprecations/gen.go
- go.mod
- go.sum
> upgrade to go1.21

- README.md
Instead of downloading the release we can install using go install
> Add the option to install using "go install"

- .gitignore
- Makefile
- Allow contributors to locally lint their changes with one command.
- Automatically install golangci-lint if not installed.
> Add lint make goal

- README.md
- docs/index.md
- docs/install.md
Very cool project!!
A few of the dependabot PRs are broken due to deprecation of "k8s.io/utils/pointer": 9588f47ce1c7db2824682d317082c59d21cc6545
I made a few README modifications as I was reading through it for the first time:
cc715a11585b0a393f3924345b780506e209ad01
> Doc clarifications and FIX lint
